# Generated by Django 5.0 on 2023-12-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_time_in',
            field=models.DateField(auto_now_add=True),
        ),
    ]
